//! Authored settlement layouts: where a city generated by
//! [`Site::generate_city`] may build, where its main plaza goes, and how many
//! buildings it must reach.
//!
//! A [`SettlementLayout`] is plain, already-resolved world-space data (the
//! authored RON lives in `civ`, which resolves it per settlement); this
//! module turns it into a per-generation [`Footprint`] in the city's own
//! tile space and answers the one question every placement hook asks:
//! *may this tile be used?* `generate_city` hooks it in five places (initial
//! plaza by anchor, plot search, plaza search, a deterministic frontier
//! plaza step, and a quota fill after the ordinary plot lottery); a city
//! without a layout never builds a footprint and generates exactly as
//! before.
//!
//! Geometry: a layout has a *frame* -- an origin in world blocks, a bank
//! direction (`along`) and the side the water lies on. A point's frame
//! coordinates are `a` (blocks toward the water) and `b` (blocks along the
//! bank). Wards are rectangles in `(a, b)`; flipping the water side mirrors
//! the whole plan across the bank line, which is how twin cities on
//! opposite banks share one ward plan.

use super::{Site, tile::TILE_SIZE};
use vek::*;

/// Which side of the frame's `along` direction the water lies on.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WaterSide {
    Left,
    Right,
}

/// Where rural plots (fields and barns, through `Site::find_rural_aabr`)
/// may go.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FieldPlacement {
    /// Anywhere in the wards, like any other plot.
    Inside,
    /// Only in a band this many tiles wide around the wards, so farms ring
    /// the town instead of taking its core.
    Ring(u32),
}

/// A layout's frame: origin, bank direction and water side, in world
/// blocks (x east, y north).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct LayoutFrame {
    pub origin_wpos: Vec2<f64>,
    /// Unit vector along the bank.
    pub along: Vec2<f64>,
    /// Unit vector toward the water: `along` turned a quarter toward the
    /// water side.
    pub toward_water: Vec2<f64>,
}

impl LayoutFrame {
    /// `along_deg` is the bank direction in degrees counter-clockwise from
    /// east. The trigonometry is [`det_sin_cos_deg`], not `f64::sin_cos`, so
    /// a ward edge cannot move a tile between platforms with different
    /// `libm`s.
    pub fn new(origin_wpos: Vec2<f64>, along_deg: f64, water_side: WaterSide) -> Self {
        let (sin, cos) = det_sin_cos_deg(along_deg);
        let along = Vec2::new(cos, sin);
        let right = Vec2::new(along.y, -along.x);
        let toward_water = match water_side {
            WaterSide::Right => right,
            WaterSide::Left => -right,
        };
        Self {
            origin_wpos,
            along,
            toward_water,
        }
    }

    /// `(a, b)`: blocks toward the water and blocks along the bank.
    pub fn to_frame(&self, wpos: Vec2<f64>) -> Vec2<f64> {
        let rel = wpos - self.origin_wpos;
        Vec2::new(rel.dot(self.toward_water), rel.dot(self.along))
    }

    /// The world position of frame coordinates `(a, b)`.
    pub fn to_world(&self, ab: Vec2<f64>) -> Vec2<f64> {
        self.origin_wpos + self.toward_water * ab.x + self.along * ab.y
    }
}

/// One ward: a half-open rectangle `a.0 <= a < a.1`, `b.0 <= b < b.1` in
/// frame blocks, with its own building target.
#[derive(Clone, Debug, PartialEq)]
pub struct LayoutWard {
    pub id: String,
    pub a: (f64, f64),
    pub b: (f64, f64),
    pub target_buildings: usize,
}

impl LayoutWard {
    pub fn contains(&self, ab: Vec2<f64>) -> bool {
        (self.a.0..self.a.1).contains(&ab.x) && (self.b.0..self.b.1).contains(&ab.y)
    }
}

/// A keep-out circle in world blocks (another settlement, a landmark).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct LayoutExclusion {
    pub centre_wpos: Vec2<i32>,
    pub radius: i32,
}

/// A settlement's resolved layout, in world space.
#[derive(Clone, Debug, PartialEq)]
pub struct SettlementLayout {
    pub frame: LayoutFrame,
    /// The main plaza's intended position, frame coordinates `(a, b)`.
    pub anchor: Vec2<f64>,
    /// The main plaza's radius in tiles; `None` keeps the generator's draw.
    pub plaza_radius: Option<u32>,
    pub fields: FieldPlacement,
    pub wards: Vec<LayoutWard>,
    pub exclusions: Vec<LayoutExclusion>,
}

impl SettlementLayout {
    pub fn target_buildings(&self) -> usize {
        self.wards.iter().map(|ward| ward.target_buildings).sum()
    }

    pub fn anchor_wpos(&self) -> Vec2<f64> { self.frame.to_world(self.anchor) }

    /// The tile the anchor falls in, for a city whose tile grid starts at
    /// `site_origin`.
    pub fn anchor_tile(&self, site_origin: Vec2<i32>) -> Vec2<i32> {
        (self.anchor_wpos() - site_origin.as_::<f64>())
            .map(|e| (e / TILE_SIZE as f64).floor() as i32)
    }

    /// Whether the anchor lies within this layout's domain around
    /// `site_origin` ([`Self::domain_tiles`]), where a footprint can use it.
    pub fn anchor_in_domain(&self, site_origin: Vec2<i32>) -> bool {
        self.anchor_tile(site_origin).map(|e| e.abs()).reduce_max()
            <= self.domain_tiles(site_origin)
    }

    /// How far from `site_origin` (Chebyshev, in tiles) the generator
    /// evaluates terrain for this layout: far enough to cover every ward, its
    /// field ring and the clear room around a plaza, but never less than an
    /// ordinary city ([`MIN_FOOTPRINT_DOMAIN_TILES`]) nor more than
    /// [`MAX_FOOTPRINT_DOMAIN_TILES`]. A ward is a rectangle, so its farthest
    /// tile is one of its corners.
    pub fn domain_tiles(&self, site_origin: Vec2<i32>) -> i32 {
        let ring = match self.fields {
            FieldPlacement::Inside => 0,
            FieldPlacement::Ring(width) => width as i32,
        };
        let extent = self
            .wards
            .iter()
            .flat_map(|ward| {
                [
                    Vec2::new(ward.a.0, ward.b.0),
                    Vec2::new(ward.a.0, ward.b.1),
                    Vec2::new(ward.a.1, ward.b.0),
                    Vec2::new(ward.a.1, ward.b.1),
                ]
            })
            .map(|corner| {
                (self.frame.to_world(corner) - site_origin.as_::<f64>())
                    .map(|e| (e / TILE_SIZE as f64).floor().abs() as i32)
                    .reduce_max()
            })
            .max()
            .unwrap_or(0);
        (extent + ring + PLAZA_ROOM_TILES)
            .clamp(MIN_FOOTPRINT_DOMAIN_TILES, MAX_FOOTPRINT_DOMAIN_TILES)
    }
}

/// The smallest domain a footprint gets (Chebyshev tiles from the site
/// origin): what an ordinary city evaluates. `Site::demarcate_obstacles`
/// stamps water, hill and route hazards on tiles `t - 1` and `t - 2` per
/// axis from a spiral over `|t| <= radius`, so the last two rows on the
/// positive side are only partly evaluated: a domain of `d` tiles needs a
/// radius of `d + 2` ([`DOMAIN_OBSTACLE_MARGIN`]).
pub const MIN_FOOTPRINT_DOMAIN_TILES: i32 =
    Site::OBSTACLE_SEARCH_RADIUS as i32 - DOMAIN_OBSTACLE_MARGIN;

/// The largest domain a footprint may get: the city's tile grid holds
/// `TILE_RADIUS` (256) tiles each way, and a plot grown at the edge of the
/// domain needs a few more.
pub const MAX_FOOTPRINT_DOMAIN_TILES: i32 = 240;

/// See [`MIN_FOOTPRINT_DOMAIN_TILES`].
pub const DOMAIN_OBSTACLE_MARGIN: i32 = 2;

/// The frontier step accepts a site whose nearest plaza is within this
/// band, in multiples of the plaza spacing: far enough not to crowd it, near
/// enough to be connected by a short street.
const FRONTIER_MIN_SPACING: f32 = 0.85;
const FRONTIER_MAX_SPACING: f32 = 3.0;

/// The largest plaza spacing `Site::make_plaza` uses, in tiles
/// (`6.5 + 3.0 * plaza_radius` with a radius of at most 2).
const MAX_PLAZA_SPACING: f32 = 12.5;

/// The radius around a new plaza within which [`Footprint`] tracks the
/// distance to the nearest plaza, in tiles: the frontier step's upper bound
/// for the largest plaza spacing.
const PLAZA_DISTANCE_TRACK_TILES: i32 = 38;
const _: () =
    assert!(PLAZA_DISTANCE_TRACK_TILES as f32 >= MAX_PLAZA_SPACING * FRONTIER_MAX_SPACING);

/// Plaza radii the frontier step is asked for (`make_plaza` draws 1 or 2;
/// an authored main plaza may be up to 3).
const MAX_PLAZA_RADIUS: usize = 3;

/// Clear ward tiles a new plaza needs on every side, so that plots have
/// room to front onto it: without it the plaza network fills the footprint's
/// leftover pockets with plazas no building can reach.
const PLAZA_ROOM_TILES: i32 = 1;

/// Which kind of plot is being searched for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Zone {
    /// Houses, workshops, taverns, plazas, ...: inside a ward.
    Built,
    /// Fields and barns: where [`FieldPlacement`] says.
    Rural,
}

const OUTSIDE: u8 = 0;
const RING: u8 = 1;
/// Cells at or above this hold `ward index + WARD_BASE`.
const WARD_BASE: u8 = 2;
/// Most wards a layout may have (one `u8` cell per tile).
pub const MAX_WARDS: usize = (u8::MAX - WARD_BASE) as usize;

/// A layout rasterised into one city's tile space for one generation.
/// Lives on [`Site::footprint`] only while `generate_city` runs.
pub struct Footprint {
    /// The layout's domain, [`SettlementLayout::domain_tiles`].
    domain: i32,
    /// Ward/ring classification of every tile within `domain` of the
    /// origin, row-major.
    cells: Vec<u8>,
    /// Squared distance (tiles²) from each cell to the nearest plaza root,
    /// tracked only up to [`PLAZA_DISTANCE_TRACK_TILES`]; `f32::INFINITY`
    /// beyond.
    plaza_dist2: Vec<f32>,
    /// Every ward tile, nearest the anchor first (ties in a fixed order):
    /// the frontier step's search order.
    ward_tiles_by_anchor_distance: Vec<Vec2<i32>>,
    pub(crate) plaza_radius: Option<u32>,
    fields: FieldPlacement,
    ward_targets: Vec<usize>,
    /// Per plaza radius: set when a frontier search found nothing; cleared
    /// by any new plaza (only a new plaza can open a new frontier position:
    /// plots only take space away).
    frontier_exhausted: [bool; MAX_PLAZA_RADIUS + 1],
    /// Plot sizes (`area_range`, `min_dims`) the roadside fill found no room
    /// for; cleared by any new plaza and its roads, the only things that add
    /// road frontage.
    fill_exhausted: Vec<(u32, u32, u32, u32)>,
}

impl Footprint {
    /// Rasterises `layout` around a city whose tile grid starts at
    /// `site_origin` (world blocks), classifying each tile by its centre.
    /// Overlapping wards are a data error (rejected when the layout is
    /// loaded); here the first ward listed would win.
    pub fn new(layout: &SettlementLayout, site_origin: Vec2<i32>) -> Self {
        assert!(layout.wards.len() <= MAX_WARDS, "too many wards");
        let domain = layout.domain_tiles(site_origin);
        let side = (2 * domain + 1) as usize;
        let mut cells = vec![OUTSIDE; side * side];
        let in_domain = |t: Vec2<i32>| t.map(|e| e.abs()).reduce_max() <= domain;
        let index = |t: Vec2<i32>| {
            let p = t + domain;
            p.y as usize * side + p.x as usize
        };
        let tile_centre = |tpos: Vec2<i32>| {
            (site_origin + tpos * TILE_SIZE as i32 + TILE_SIZE as i32 / 2).as_::<f64>()
        };
        // Only the exclusions that reach the domain.
        let reach = (domain + 1) * TILE_SIZE as i32;
        let exclusions: Vec<_> = layout
            .exclusions
            .iter()
            .filter(|ex| {
                (ex.centre_wpos - site_origin).map(i32::abs).reduce_max() < reach + ex.radius
            })
            .collect();
        let excluded = |wpos: Vec2<f64>| {
            exclusions.iter().any(|ex| {
                let r = ex.radius as f64;
                wpos.distance_squared(ex.centre_wpos.as_()) < r * r
            })
        };
        let mut ward_tiles = Vec::new();
        for y in -domain..=domain {
            for x in -domain..=domain {
                let tpos = Vec2::new(x, y);
                let wpos = tile_centre(tpos);
                if excluded(wpos) {
                    continue;
                }
                let ab = layout.frame.to_frame(wpos);
                if let Some(i) = layout.wards.iter().position(|ward| ward.contains(ab)) {
                    cells[index(tpos)] = WARD_BASE + i as u8;
                    ward_tiles.push(tpos);
                }
            }
        }
        if let FieldPlacement::Ring(width) = layout.fields {
            let width = width as i32;
            for &tpos in &ward_tiles {
                for dy in -width..=width {
                    for dx in -width..=width {
                        let t = tpos + Vec2::new(dx, dy);
                        if in_domain(t) && cells[index(t)] == OUTSIDE && !excluded(tile_centre(t)) {
                            cells[index(t)] = RING;
                        }
                    }
                }
            }
        }
        let anchor_tile = layout.anchor_tile(site_origin);
        // `ward_tiles` is in row-major order, so the stable sort breaks
        // distance ties the same way every time.
        ward_tiles.sort_by_key(|t| (*t - anchor_tile).magnitude_squared());
        Self {
            domain,
            cells,
            plaza_dist2: vec![f32::INFINITY; side * side],
            ward_tiles_by_anchor_distance: ward_tiles,
            plaza_radius: layout.plaza_radius,
            fields: layout.fields,
            ward_targets: layout.wards.iter().map(|w| w.target_buildings).collect(),
            frontier_exhausted: [false; MAX_PLAZA_RADIUS + 1],
            fill_exhausted: Vec::new(),
        }
    }

    /// The layout's domain in tiles ([`SettlementLayout::domain_tiles`]).
    pub fn domain_tiles(&self) -> i32 { self.domain }

    fn in_domain(&self, tpos: Vec2<i32>) -> bool {
        tpos.map(|e| e.abs()).reduce_max() <= self.domain
    }

    fn index(&self, tpos: Vec2<i32>) -> usize {
        let p = tpos + self.domain;
        (p.y * (2 * self.domain + 1) + p.x) as usize
    }

    fn cell(&self, tpos: Vec2<i32>) -> u8 {
        if self.in_domain(tpos) {
            self.cells[self.index(tpos)]
        } else {
            OUTSIDE
        }
    }

    /// The ward a tile belongs to, by index into the layout's wards.
    pub fn ward_of(&self, tpos: Vec2<i32>) -> Option<usize> {
        self.cell(tpos).checked_sub(WARD_BASE).map(usize::from)
    }

    /// Whether a plot of `zone` may use this tile.
    pub(crate) fn allows(&self, tpos: Vec2<i32>, zone: Zone) -> bool {
        let cell = self.cell(tpos);
        match (zone, self.fields) {
            (Zone::Rural, FieldPlacement::Ring(_)) => cell == RING,
            _ => cell >= WARD_BASE,
        }
    }

    /// Whether every tile of a plaza patch lies in the wards.
    #[cfg(test)]
    fn allows_patch(&self, aabr: Aabr<i32>) -> bool {
        (aabr.min.y..aabr.max.y)
            .all(|y| (aabr.min.x..aabr.max.x).all(|x| self.allows(Vec2::new(x, y), Zone::Built)))
    }

    /// Whether a plaza patch lies in the wards with [`PLAZA_ROOM_TILES`] of
    /// clear ward tiles around it. `is_clear` judges the ring only; the
    /// caller judges the patch itself.
    pub(crate) fn has_room_for_plaza(
        &self,
        aabr: Aabr<i32>,
        is_clear: impl Fn(Vec2<i32>) -> bool,
    ) -> bool {
        let outer = Aabr {
            min: aabr.min - PLAZA_ROOM_TILES,
            max: aabr.max + PLAZA_ROOM_TILES,
        };
        (outer.min.y..outer.max.y).all(|y| {
            (outer.min.x..outer.max.x).all(|x| {
                let t = Vec2::new(x, y);
                let in_patch =
                    (aabr.min.x..aabr.max.x).contains(&x) && (aabr.min.y..aabr.max.y).contains(&y);
                self.allows(t, Zone::Built) && (in_patch || is_clear(t))
            })
        })
    }

    /// Every ward tile, nearest the anchor first.
    pub(crate) fn ward_tiles(&self) -> impl Iterator<Item = Vec2<i32>> + '_ {
        self.ward_tiles_by_anchor_distance.iter().copied()
    }

    /// Records a new plaza rooted at `root` for the frontier step.
    pub(crate) fn note_plaza(&mut self, root: Vec2<i32>) {
        self.frontier_exhausted = [false; MAX_PLAZA_RADIUS + 1];
        self.fill_exhausted.clear();
        let r = PLAZA_DISTANCE_TRACK_TILES;
        for y in -r..=r {
            for x in -r..=r {
                let t = root + Vec2::new(x, y);
                if self.in_domain(t) {
                    let d2 = (x * x + y * y) as f32;
                    let i = self.index(t);
                    let cell = &mut self.plaza_dist2[i];
                    *cell = cell.min(d2);
                }
            }
        }
    }

    /// The main plaza's patch: the clear patch nearest the anchor. Draws no
    /// random numbers.
    pub(crate) fn initial_plaza(
        &self,
        plaza_radius: i32,
        is_clear: impl Fn(Vec2<i32>) -> bool,
    ) -> Option<Aabr<i32>> {
        self.nearest_patch_to_anchor(plaza_radius, |_| true, is_clear)
    }

    /// The deterministic frontier step: the clear plaza patch nearest the
    /// anchor whose nearest plaza is between [`FRONTIER_MIN_SPACING`] and
    /// [`FRONTIER_MAX_SPACING`] times `plaza_dist` away. Draws no random
    /// numbers.
    pub(crate) fn frontier_plaza(
        &mut self,
        plaza_radius: i32,
        plaza_dist: f32,
        is_clear: impl Fn(Vec2<i32>) -> bool,
    ) -> Option<Aabr<i32>> {
        let slot = (plaza_radius.max(0) as usize).min(MAX_PLAZA_RADIUS);
        if self.frontier_exhausted[slot] {
            return None;
        }
        let (min, max) = (
            plaza_dist * FRONTIER_MIN_SPACING,
            plaza_dist * FRONTIER_MAX_SPACING,
        );
        let (min2, max2) = (min * min, max * max);
        let found = self.nearest_patch_to_anchor(
            plaza_radius,
            |centre| {
                let d2 = self.plaza_dist2[self.index(centre)];
                d2 > min2 && d2 <= max2
            },
            is_clear,
        );
        self.frontier_exhausted[slot] = found.is_none();
        found
    }

    /// Whether the roadside fill already found no room for this plot size
    /// since the last new plaza.
    pub(crate) fn fill_exhausted(
        &self,
        area_range: &std::ops::Range<u32>,
        min_dims: Extent2<u32>,
    ) -> bool {
        self.fill_exhausted
            .contains(&(area_range.start, area_range.end, min_dims.w, min_dims.h))
    }

    /// Records that the roadside fill found no room for this plot size.
    pub(crate) fn note_fill_exhausted(
        &mut self,
        area_range: &std::ops::Range<u32>,
        min_dims: Extent2<u32>,
    ) {
        self.fill_exhausted
            .push((area_range.start, area_range.end, min_dims.w, min_dims.h));
    }

    /// The first ward patch, in anchor-distance order, whose centre passes
    /// `accept` and whose tiles, and room around them, are all in the wards
    /// and clear.
    fn nearest_patch_to_anchor(
        &self,
        plaza_radius: i32,
        accept: impl Fn(Vec2<i32>) -> bool,
        is_clear: impl Fn(Vec2<i32>) -> bool,
    ) -> Option<Aabr<i32>> {
        self.ward_tiles_by_anchor_distance
            .iter()
            .filter(|&&centre| accept(centre))
            .map(|&centre| Aabr {
                min: centre - plaza_radius,
                max: centre + plaza_radius + 1,
            })
            .find(|&aabr| {
                (aabr.min.y..aabr.max.y)
                    .all(|y| (aabr.min.x..aabr.max.x).all(|x| is_clear(Vec2::new(x, y))))
                    && self.has_room_for_plaza(aabr, &is_clear)
            })
    }

    /// Buildings per ward, counting each building by the ward of its root
    /// tile; buildings outside every ward count for none.
    pub fn buildings_per_ward(
        &self,
        building_roots: impl Iterator<Item = Vec2<i32>>,
    ) -> Vec<usize> {
        let mut counts = vec![0usize; self.ward_targets.len()];
        for root in building_roots {
            if let Some(ward) = self.ward_of(root) {
                counts[ward] += 1;
            }
        }
        counts
    }

    /// Tiles per ward that the footprint can use: inside the evaluated
    /// domain and outside every exclusion.
    pub fn usable_tiles_per_ward(&self) -> Vec<usize> {
        let mut counts = vec![0usize; self.ward_targets.len()];
        for &tile in &self.ward_tiles_by_anchor_distance {
            if let Some(ward) = self.ward_of(tile) {
                counts[ward] += 1;
            }
        }
        counts
    }

    /// Whether every ward has reached its building target.
    pub(crate) fn quota_met(&self, building_roots: impl Iterator<Item = Vec2<i32>>) -> bool {
        self.buildings_per_ward(building_roots)
            .iter()
            .zip(&self.ward_targets)
            .all(|(count, target)| count >= target)
    }

    pub fn target_buildings(&self) -> usize { self.ward_targets.iter().sum() }
}

/// `(sin, cos)` of an angle in degrees using only IEEE-754 basic operations
/// (correctly rounded on every platform), unlike `f64::sin_cos`, whose last
/// bit depends on the platform's `libm`. The angle is reduced to within 45°
/// of a multiple of 90° first, so the series below is accurate to ~1e-16.
pub fn det_sin_cos_deg(deg: f64) -> (f64, f64) {
    let d = deg.rem_euclid(360.0);
    let quadrant = ((d / 90.0).round() as i64).rem_euclid(4);
    let x = (d - (d / 90.0).round() * 90.0) * (std::f64::consts::PI / 180.0);
    let x2 = x * x;
    // Taylor series up to x^17 (sin) and x^16 (cos): with |x| <= pi/4 the
    // first omitted term is below 1e-16.
    let mut sin = 0.0;
    let mut cos = 0.0;
    let mut term_s = x;
    let mut term_c = 1.0;
    for n in 0..9 {
        sin += term_s;
        cos += term_c;
        let k = 2.0 * n as f64;
        term_s *= -x2 / ((k + 2.0) * (k + 3.0));
        term_c *= -x2 / ((k + 1.0) * (k + 2.0));
    }
    match quadrant {
        0 => (sin, cos),
        1 => (cos, -sin),
        2 => (-sin, -cos),
        _ => (-cos, sin),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn layout(water_side: WaterSide) -> SettlementLayout {
        SettlementLayout {
            frame: LayoutFrame::new(Vec2::new(1000.0, 1000.0), 0.0, water_side),
            anchor: Vec2::new(-30.0, 15.0),
            plaza_radius: Some(1),
            fields: FieldPlacement::Inside,
            wards: vec![
                LayoutWard {
                    id: "inner".into(),
                    a: (-120.0, 0.0),
                    b: (0.0, 60.0),
                    target_buildings: 7,
                },
                LayoutWard {
                    id: "outer".into(),
                    a: (-120.0, 0.0),
                    b: (60.0, 120.0),
                    target_buildings: 3,
                },
            ],
            exclusions: Vec::new(),
        }
    }

    #[test]
    fn det_sin_cos_matches_libm() {
        for deg in (-720..=720).map(|d| d as f64 * 0.37) {
            let (s, c) = det_sin_cos_deg(deg);
            let (rs, rc) = deg.to_radians().sin_cos();
            assert!((s - rs).abs() < 1e-12 && (c - rc).abs() < 1e-12, "{deg}");
        }
        assert_eq!(det_sin_cos_deg(90.0), (1.0, 0.0));
        assert_eq!(det_sin_cos_deg(-90.0), (-1.0, 0.0));
        assert_eq!(det_sin_cos_deg(0.0), (0.0, 1.0));
    }

    #[test]
    fn frame_round_trips_and_water_side_mirrors() {
        let right = LayoutFrame::new(Vec2::new(10.0, 20.0), -29.78, WaterSide::Right);
        let left = LayoutFrame::new(Vec2::new(10.0, 20.0), -29.78, WaterSide::Left);
        let p = Vec2::new(-130.0, 77.0);
        let ab = right.to_frame(p);
        assert!(right.to_world(ab).distance(p) < 1e-9);
        // Same along coordinate, opposite toward-water coordinate.
        let ab_left = left.to_frame(p);
        assert!((ab.x + ab_left.x).abs() < 1e-9 && (ab.y - ab_left.y).abs() < 1e-9);
        // Along east, water on the right = south.
        let east = LayoutFrame::new(Vec2::zero(), 0.0, WaterSide::Right);
        assert!(east.toward_water.distance(Vec2::new(0.0, -1.0)) < 1e-12);
    }

    #[test]
    fn footprint_classifies_wards_and_mirrors() {
        // Along east, water south (Right): wards lie at a in [-60, 0), i.e.
        // north of the origin, and east of it.
        let fp = Footprint::new(&layout(WaterSide::Right), Vec2::new(1000, 1000));
        assert_eq!(fp.ward_of(Vec2::new(2, 2)), Some(0));
        assert_eq!(fp.ward_of(Vec2::new(12, 2)), Some(1));
        assert_eq!(fp.ward_of(Vec2::new(2, -2)), None);
        assert_eq!(fp.ward_of(Vec2::new(-2, 2)), None);
        let origin = Vec2::new(1000, 1000);
        assert_eq!(
            layout(WaterSide::Right).anchor_tile(origin),
            Vec2::new(2, 5)
        );
        assert_eq!(fp.target_buildings(), 10);
        // Water on the left (north) mirrors the plan south.
        let fp = Footprint::new(&layout(WaterSide::Left), Vec2::new(1000, 1000));
        assert_eq!(fp.ward_of(Vec2::new(2, -3)), Some(0));
        assert_eq!(fp.ward_of(Vec2::new(2, 2)), None);
        assert_eq!(
            layout(WaterSide::Left).anchor_tile(origin),
            Vec2::new(2, -5)
        );
    }

    #[test]
    fn footprint_honours_exclusions_ring_and_domain() {
        let mut l = layout(WaterSide::Right);
        l.exclusions.push(LayoutExclusion {
            centre_wpos: Vec2::new(1015, 1015),
            radius: 10,
        });
        l.fields = FieldPlacement::Ring(2);
        let fp = Footprint::new(&l, Vec2::new(1000, 1000));
        assert_eq!(fp.ward_of(Vec2::new(2, 2)), None, "excluded");
        assert!(!fp.allows(Vec2::new(2, 2), Zone::Built));
        assert!(fp.allows(Vec2::new(5, 5), Zone::Built));
        assert!(
            !fp.allows(Vec2::new(5, 5), Zone::Rural),
            "fields only in the ring"
        );
        assert!(fp.allows(Vec2::new(5, -1), Zone::Rural));
        assert!(
            !fp.allows(Vec2::new(5, -3), Zone::Rural),
            "ring is 2 tiles wide"
        );
        // The domain follows the wards (here 120 blocks = 20 tiles, under
        // the minimum) but never passes the maximum, however large the ward.
        assert_eq!(fp.domain_tiles(), MIN_FOOTPRINT_DOMAIN_TILES);
        l.wards[1].b = (60.0, 900.0);
        let fp = Footprint::new(&l, Vec2::new(1000, 1000));
        // 900 blocks = tile 150, plus the 2-tile ring and the plaza room.
        assert_eq!(fp.domain_tiles(), 153);
        assert!(fp.allows(Vec2::new(149, 2), Zone::Built));
        assert!(!fp.allows(Vec2::new(150, 2), Zone::Built));
        l.wards[1].b = (60.0, 1.0e6);
        let fp = Footprint::new(&l, Vec2::new(1000, 1000));
        assert_eq!(fp.domain_tiles(), MAX_FOOTPRINT_DOMAIN_TILES);
        assert!(fp.allows(Vec2::new(MAX_FOOTPRINT_DOMAIN_TILES, 2), Zone::Built));
        assert!(!fp.allows(Vec2::new(MAX_FOOTPRINT_DOMAIN_TILES + 1, 2), Zone::Built));
    }

    #[test]
    fn frontier_grows_from_the_anchor_at_plaza_spacing() {
        let mut fp = Footprint::new(&layout(WaterSide::Right), Vec2::new(1000, 1000));
        // The main plaza: the patch nearest the anchor (2, 5) with a clear
        // ring of `PLAZA_ROOM_TILES` inside the wards (which start at x = 0).
        assert_eq!(PLAZA_ROOM_TILES, 1);
        let first = fp.initial_plaza(1, |_| true).unwrap();
        assert_eq!(first.center(), Vec2::new(2, 5));
        let blocked = fp.initial_plaza(1, |t| t.y > 5).unwrap();
        assert_eq!(blocked.center(), Vec2::new(2, 8));
        fp.note_plaza(first.center());
        let second = fp.frontier_plaza(1, 9.5, |_| true).unwrap();
        let d2 = (second.center() - first.center()).magnitude_squared() as f32;
        let (min, max) = (9.5 * FRONTIER_MIN_SPACING, 9.5 * FRONTIER_MAX_SPACING);
        assert!(d2 > min * min && d2 <= max * max);
        assert!(fp.allows_patch(second));
        // Nothing clear: exhausted until the next plaza.
        assert_eq!(fp.frontier_plaza(1, 9.5, |_| false), None);
        assert_eq!(fp.frontier_plaza(1, 9.5, |_| true), None);
        fp.note_plaza(second.center());
        assert!(fp.frontier_plaza(1, 9.5, |_| true).is_some());
    }

    #[test]
    fn quota_counts_buildings_per_ward() {
        let fp = Footprint::new(&layout(WaterSide::Right), Vec2::new(1000, 1000));
        let inner = std::iter::repeat_n(Vec2::new(2, 2), 7);
        let outer = std::iter::repeat_n(Vec2::new(12, 2), 3);
        assert!(fp.quota_met(inner.clone().chain(outer.clone())));
        assert!(!fp.quota_met(inner.clone().chain(outer.clone().take(2))));
        // Buildings outside every ward count for none.
        assert!(!fp.quota_met(inner.chain(std::iter::repeat_n(Vec2::new(-5, -5), 9))));
    }
}
