[package]
name = "xindeler-server-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
worldgen = []
use-dyn-lib = ["common-dynlib"]
be-dyn-lib = []

[dependencies]
common = { package = "xindeler-common", path = "../../common" }
common-base = { package = "xindeler-common-base", path = "../../common/base" }
common-dynlib = { package = "xindeler-common-dynlib", path = "../../common/dynlib", optional = true }
world = { package = "xindeler-world", path = "../../world" }
rtsim = { package = "xindeler-rtsim", path = "../../rtsim" }

specs = { workspace = true, features = ["shred-derive"] }
vek = { workspace = true }
rand = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
tracing = { workspace = true }
